"""Link TagLabel and Category tables.

Revision ID: 242ff2c2dd67
Revises: 6e7c22fd38b8
Create Date: 2023-08-11 16:16:00.664455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242ff2c2dd67'
down_revision = '6e7c22fd38b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taglabels', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'taglabels', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taglabels', type_='foreignkey')
    op.drop_column('taglabels', 'category_id')
    # ### end Alembic commands ###
