"""Link Restaurant to a root category for the restaurant

Revision ID: 462497bbd403
Revises: 242ff2c2dd67
Create Date: 2023-08-11 19:22:35.692000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462497bbd403'
down_revision = '242ff2c2dd67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_restaurant_id'), 'categories', ['restaurant_id'], unique=True)
    op.create_foreign_key(None, 'categories', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_restaurant_id'), table_name='categories')
    op.drop_column('categories', 'restaurant_id')
    # ### end Alembic commands ###
