"""Added categories table

Revision ID: 5f9d1cd8e78f
Revises: 8ead7a7067d5
Create Date: 2023-08-10 18:21:41.654206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9d1cd8e78f'
down_revision = '8ead7a7067d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuitems', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menuitems', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menuitems', type_='foreignkey')
    op.drop_column('menuitems', 'category_id')
    # ### end Alembic commands ###
