"""Add required field to Tag model

Revision ID: 8ead7a7067d5
Revises: b8da26d716c9
Create Date: 2023-08-07 19:38:03.798158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ead7a7067d5'
down_revision = 'b8da26d716c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('required', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'required')
    # ### end Alembic commands ###
