"""Get DB up to date with model definitions

Revision ID: b8da26d716c9
Revises: 767a52c3173f
Create Date: 2023-08-07 19:24:45.280284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8da26d716c9'
down_revision = '767a52c3173f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'itemtags', 'tags', ['tag_id'], ['id'])
    op.alter_column('menuitems', 'item_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_16489_ix_menuitems_item_name', table_name='menuitems')
    op.create_index(op.f('ix_menuitems_id'), 'menuitems', ['id'], unique=False)
    op.create_index(op.f('ix_menuitems_item_name'), 'menuitems', ['item_name'], unique=True)
    op.alter_column('restaurants', 'restaurant_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_16484_ix_restaurants_restaurant_name', table_name='restaurants')
    op.create_index(op.f('ix_restaurants_restaurant_name'), 'restaurants', ['restaurant_name'], unique=True)
    op.alter_column('tags', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tags', 'is_leaf',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_16502_ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index('idx_16502_ix_tags_name', 'tags', ['name'], unique=False)
    op.alter_column('tags', 'is_leaf',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tags', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_restaurants_restaurant_name'), table_name='restaurants')
    op.create_index('idx_16484_ix_restaurants_restaurant_name', 'restaurants', ['restaurant_name'], unique=False)
    op.alter_column('restaurants', 'restaurant_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_menuitems_item_name'), table_name='menuitems')
    op.drop_index(op.f('ix_menuitems_id'), table_name='menuitems')
    op.create_index('idx_16489_ix_menuitems_item_name', 'menuitems', ['item_name'], unique=False)
    op.alter_column('menuitems', 'item_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'itemtags', type_='foreignkey')
    # ### end Alembic commands ###
