"""Rename root_tag_id to root_category_id

Revision ID: e0649c80dd59
Revises: ca178b8f6917
Create Date: 2023-08-15 22:23:15.071667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0649c80dd59'
down_revision = 'ca178b8f6917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the root_category_id column as nullable
    op.add_column('restaurants', sa.Column('root_category_id', sa.Integer(), nullable=True))
    
    # Update all the existing rows to set root_category_id to 1
    op.execute('UPDATE restaurants SET root_category_id = 1')
    
    # Alter the root_category_id column to set it as non-nullable
    op.alter_column('restaurants', 'root_category_id', nullable=False)
    op.drop_index('ix_restaurants_root_tag_id', table_name='restaurants')
    op.create_index(op.f('ix_restaurants_root_category_id'), 'restaurants', ['root_category_id'], unique=False)
    op.drop_constraint('fk_restaurants_root_tag_id', 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'categories', ['root_category_id'], ['id'])
    op.drop_column('restaurants', 'root_tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('root_tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key('fk_restaurants_root_tag_id', 'restaurants', 'categories', ['root_tag_id'], ['id'])
    op.drop_index(op.f('ix_restaurants_root_category_id'), table_name='restaurants')
    op.create_index('ix_restaurants_root_tag_id', 'restaurants', ['root_tag_id'], unique=False)
    op.drop_column('restaurants', 'root_category_id')
    # ### end Alembic commands ###
