import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className='navigation'>
        <Link href='/menu' className='logo'>Meenew</Link>
      </nav>
      {children}
      <nav className='footer'>
        ©Meenew all rights reserved
      </nav>
      </body>
    </html>
  )
}
